@extends('site.partials.app')
@section('title') {{ $pageTitle }} @endsection
@section('content')

<section class="gry-bg py-4">
   <div class="container">
      <div class="row">
         <div class="col">
            <div class="p-4 bg-white">
               <div class="page-title-wrapper" style="box-sizing: border-box; color: rgb(102, 102, 102); font-family: &quot;Open Sans&quot;; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                  <h1 class="page-title" style="box-sizing: border-box; font-weight: 600; line-height: 1.25em; font-size: 21.658px; margin: 0px 0px 15px; font-family: inherit; color: rgb(255, 195, 79); text-transform: uppercase;"><span class="base" data-ui-id="page-title-wrapper" style="box-sizing: border-box;">SHIPPING &amp; DELIVERY POLICY</span></h1>
               </div>
               <div class="page messages" style="box-sizing: border-box; color: rgb(102, 102, 102); font-family: &quot;Open Sans&quot;; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                  <div data-placeholder="messages" style="box-sizing: border-box;"><br></div>
                  <div data-bind="scope: 'messages'" style="box-sizing: border-box;"><br></div>
               </div>
               <div class="column main" style="box-sizing: border-box; max-width: 100%; color: rgb(102, 102, 102); font-family: &quot;Open Sans&quot;; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                  <div style="box-sizing: border-box; clear: both;"><br></div>
                  <p style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 13px;"><b style="box-sizing: border-box; font-weight: bold;">SHIPPING &amp; DELIVERY POLICY</b></p>
                  <p style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 13px;">mashroostore.com is committed to deliver your order with good quality packaging within the given time frame. Our current turn around time is one day. For India we deliver within 5&nbsp;-7&nbsp;working days and Rest of the World 4-12 working days depending on the shipping method selected at check out . We ship throughout the week, except Sunday &amp;Indian public holidays. To ensure that your order reaches you in good condition, in the shortest span of time, we ship through reliable shipping &amp; logistics companies like Fedex , DHL ,UPS, Bluedart etc.</p>
                  <p style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 13px;"><b style="box-sizing: border-box; font-weight: bold;">How the delivery charge is calculated for multiple units?</b></p>
                  <p style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 13px;">The shipping charge is specified separately for every product. For multiple products ordered the program adds up the total of all individual shipping charges. Thus, a customer who orders three products is charged the total of all individual delivery charges associated with each product. Thus the delivery fee is calculated separately when a customer orders different products .</p>
                  <p style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 13px;">Our prices are all inclusive. All taxes are included with the list prices except local custom the duties, if applicable in your region.</p>
                  <p style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 13px;"><b style="box-sizing: border-box; font-weight: bold;">How long does it take for an order to arrive?</b></p>
                  <p style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 13px;">Orders are dispatched within two days from date order is placed .Orders are delivered within 5&nbsp;to 7&nbsp;working days for India &amp; 4-12 working days for Rest of the World. Delivery of all orders will be duly done to the address as mentioned by you at the time of placing the order.</p>
                  <p style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 13px;"><b style="box-sizing: border-box; font-weight: bold;">What if I the product is received in damaged condition?</b></p>
                  <p style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 13px;">If you think, you have received the product in a bad condition or if the packaging is tampered with or damaged before delivery, please refuse to accept the package and return the package to the delivery person. Also, please call our customer care at 18001029969 or email us at info@mashroo.in mentioning your Order ID. We will personally ensure that a brand new replacement is issued to you with no additional cost. Please make sure that the original product tag and packing is intact when you send us the product back.</p>
                  <p style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 13px;"><b style="box-sizing: border-box; font-weight: bold;">About Customs, Duties &amp; Taxes</b></p>
                  <p style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 13px;">When ordering from www.mashroostore.com, you're responsible for assuring the product can be lawfully imported to the destination.</p>
                  <p style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 13px;">The recipient is the importer of record and must comply with all laws and regulations of the destination. Orders shipped outside of&nbsp;India&nbsp;may be subject to import taxes, customs duties and fees levied by the destination country. The recipient of an international shipment may be subject to such import taxes, customs duties and fees, which are levied once a shipment reaches the recipient's country. Additional charges for customs clearance must be fulfilled by the recipient; mashroostore.com has no control over these charges, nor can mashroostore.com predict what they may be.</p>
                  <p style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 13px;">Customs policies vary widely; you should contact your local customs office for more information. When customs clearance procedures are required, it can cause delays beyond our original delivery estimates.</p>
                  <p style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 13px;"><b style="box-sizing: border-box; font-weight: bold;">Note:</b></p>
                  <p style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 13px;">Customs offices in some countries or regions require the importer of record to provide a particular form of identification before releasing a shipment. You may be required to provide an identification number such as a Unique Identification Number, CPF, or Tax ID.</p>
                  <p style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 13px;">Countries / regions that require an identification number include: Brazil, Chile, China, Ecuador, Israel, Peru, Qatar, South Africa, South Korea, Taiwan, and Turkey.</p>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>
@endsection